name: groupcomm-solutions 

on:
  push:
    branches:
      - main

jobs:

  # Build and test the applications with multiple Java versions
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [
          '8.0.x',
          '9.0.x',
          '11.0.x',
          '12.0.x',
          '13.0.x',
          '14.0.x',
          '15.0.x',
        ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'

      - name: Build for Eclipse
        run: |
          ./config.sh

      - name: Run Californium & ACE JUnit tests
        run: |
          ./test-californium.sh
          ./test-ace.sh --with-mysql
          ./code-coverage.sh

      - name: Generate Jacoco Badge (EDHOC)
        id: jacoco-edhoc
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: jacoco/edhoc/jacoco.csv
          coverage-badge-filename: jacoco-edhoc.svg
          coverage-label: EDHOC

      - name: Generate Jacoco Badge (OSCORE & Group OSCORE)
        id: jacoco-oscore
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: jacoco/oscore/jacoco.csv
          coverage-badge-filename: jacoco-oscore.svg
          coverage-label: OSCORE and Group OSCORE

      - name: Generate Jacoco Badge (ACE & Group Joining)
        id: jacoco-ace
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: jacoco/ace/jacoco.csv
          coverage-badge-filename: jacoco-ace.svg
          coverage-label: ACE and Group Joining

      - name: Move the badges to jacoco folder
        run: |
          mv .github/badges/*.svg jacoco/

      - name: Deploy Jacoco code coverage reports to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ matrix.java-version == '8.0.x' }}
        with:
          token: ${{ secrets.GH_PAT }}
          clean: true
          folder: jacoco
          target-folder: reports
          branch: gh-pages

